// <auto-generated />
namespace Foostats2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedApi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedApi));
        
        string IMigrationMetadata.Id
        {
            get { return "201311150942241_AddedApi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
